[package]
name = "rock_paper_scissors"
version = "0.1.0"
authors = ["Dowland Aiello <mitsukomegumii@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
